import type { Metadata } from 'next'

import './globals.css'
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center items-center   h-screen ">
          <div className="h-[70vh] flex flex-col  bg-gray-500 rounded-xl max-w-[500px]">
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
